version: 0.0
os: linux
files:
  - source: ./
    destination: /home/ec2-user/webapp
    overwrite: true
    file_exists_behavior: OVERWRITE
    
hooks:
  BeforeInstall:
    - location: ./codedeploy/beforeInstall.sh
      timeout: 180
  AfterInstall:
    - location: ./codedeploy/afterInstall.sh
      timeout: 180
  ApplicationStart:
    - location: ./codedeploy/applicationStart.sh
      timeout: 180
  ApplicationStop:
    - location: ./codedeploy/applicationStop.sh
      timeout: 180      